# Generated by Django 5.0.6 on 2024-06-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worldborder",
            name="fips",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="FIPS Code"
            ),
        ),
    ]
